version: '3.9'

name: webshop

services:
  db:
    image: mysql:8.0
    container_name: miniweb_db
    restart: always
    env_file:
      - ./db/.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - webshop_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 8s
      timeout: 8s
      retries: 12

  backend:
    build: ./backend
    container_name: miniweb_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    networks:
      - webshop_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: miniweb_frontend
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    networks:
      - webshop_network
    depends_on:
      - backend


volumes:
  db_data:

networks:
  webshop_network:
    driver: bridge
