version: '3.9'

name: webshop

services:
  db:
    image: mysql:8.0
    container_name: miniweb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mini_webshop
      MYSQL_USER: webshop
      MYSQL_PASSWORD: webshoppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 8s
      timeout: 8s
      retries: 12

  backend:
    build: ./backend
    container_name: miniweb_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: webshop
      DB_PASSWORD: webshoppass
      DB_NAME: mini_webshop
      DB_PORT: 3306
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: miniweb_frontend
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - backend


volumes:
  db_data:
