# Koristimo zvanični Node.js image
FROM node:20

# Postavljamo radni direktorijum u kontejneru
WORKDIR /app

# Kopiramo package.json i package-lock.json
COPY package*.json ./

# Instaliramo zavisnosti
RUN npm install
RUN npm install --save-dev nodemon
# Kopiramo ceo backend kod u kontejner
COPY . .

# Ekspozujemo port 3000
EXPOSE 3000

# Startujemo server
CMD ["npx", "nodemon", "server.js"]
